services:
  php:
    build: .
    volumes:
      - .:/app
      - vendor:/app/vendor
    working_dir: /app
    networks:
      - app

  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/app
      - vendor:/app/vendor
    depends_on:
      - php
    networks:
      - app

networks:
  app:

volumes:
  vendor:
